/**
 * AUTO-GENERATED by tools/build-asset-manifest.ts — do not edit by hand.
 * Runtime loading data for processed assets (URLs relative to the public root).
 */

export interface ProcessedAnimation {
  url: string;
  source: string;
  /** baked standing height in texture px — runtime scale = worldHeight / this */
  bakedStandingPx?: number;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  fps: number;
  loop: boolean;
}

export interface ProcessedStill {
  url: string;
  source: string;
  width: number;
  height: number;
  /** true when the runtime file is a byte-for-byte copy of the source */
  passthrough?: boolean;
  /** visible (non-transparent) bounds inside the image */
  contentRect?: { x: number; y: number; w: number; h: number };
}

export const PROCESSED_ANIMATIONS = {
  "characters.guardian.attack": {
    "url": "characters/guardian/attack.png",
    "source": "Assets/sprites/guardian/19_guardian_attack_01_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 624,
    "frameHeight": 521,
    "frameCount": 8,
    "fps": 11,
    "loop": false
  },
  "characters.guardian.attack2": {
    "url": "characters/guardian/attack2.png",
    "source": "Assets/sprites/guardian/20_guardian_attack_02_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 646,
    "frameHeight": 536,
    "frameCount": 8,
    "fps": 11,
    "loop": false
  },
  "characters.guardian.block": {
    "url": "characters/guardian/block.png",
    "source": "Assets/sprites/guardian/21_guardian_block_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 548,
    "frameHeight": 482,
    "frameCount": 6,
    "fps": 10,
    "loop": true
  },
  "characters.guardian.defeat": {
    "url": "characters/guardian/defeat.png",
    "source": "Assets/sprites/guardian/24_guardian_defeat_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 789,
    "frameHeight": 459,
    "frameCount": 6,
    "fps": 9,
    "loop": false
  },
  "characters.guardian.hit": {
    "url": "characters/guardian/hit.png",
    "source": "Assets/sprites/guardian/22_guardian_hit_reaction_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 581,
    "frameHeight": 468,
    "frameCount": 6,
    "fps": 12,
    "loop": false
  },
  "characters.guardian.idle": {
    "url": "characters/guardian/idle.png",
    "source": "Assets/sprites/guardian/16_guardian_idle_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 602,
    "frameHeight": 494,
    "frameCount": 8,
    "fps": 8,
    "loop": true
  },
  "characters.guardian.knockdown": {
    "url": "characters/guardian/knockdown.png",
    "source": "Assets/sprites/guardian/23_guardian_knockdown_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 644,
    "frameHeight": 440,
    "frameCount": 7,
    "fps": 9,
    "loop": false
  },
  "characters.guardian.run": {
    "url": "characters/guardian/run.png",
    "source": "Assets/sprites/guardian/18_guardian_run_charge_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 718,
    "frameHeight": 506,
    "frameCount": 8,
    "fps": 10,
    "loop": true
  },
  "characters.guardian.walk": {
    "url": "characters/guardian/walk.png",
    "source": "Assets/sprites/guardian/17_guardian_walk_forward_hd_sheet.png",
    "bakedStandingPx": 482,
    "frameWidth": 655,
    "frameHeight": 499,
    "frameCount": 8,
    "fps": 8,
    "loop": true
  },
  "characters.kairo.attack1": {
    "url": "characters/kairo/attack1.png",
    "source": "Assets/sprites/kairo/kairo_attack_02_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 442,
    "frameHeight": 435,
    "frameCount": 4,
    "fps": 14,
    "loop": false
  },
  "characters.kairo.attack2": {
    "url": "characters/kairo/attack2.png",
    "source": "Assets/sprites/kairo/kairo_attack_02_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 652,
    "frameHeight": 409,
    "frameCount": 3,
    "fps": 14,
    "loop": false
  },
  "characters.kairo.block": {
    "url": "characters/kairo/block.png",
    "source": "Assets/sprites/kairo/kairo_block_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 533,
    "frameHeight": 417,
    "frameCount": 4,
    "fps": 10,
    "loop": true
  },
  "characters.kairo.dash": {
    "url": "characters/kairo/dash.png",
    "source": "Assets/sprites/kairo/05_kairo_dash_forward_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 857,
    "frameHeight": 426,
    "frameCount": 6,
    "fps": 14,
    "loop": false
  },
  "characters.kairo.getup": {
    "url": "characters/kairo/getup.png",
    "source": "Assets/sprites/kairo/kairo_get_up_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 485,
    "frameHeight": 386,
    "frameCount": 6,
    "fps": 10,
    "loop": false
  },
  "characters.kairo.heavy": {
    "url": "characters/kairo/heavy.png",
    "source": "Assets/sprites/kairo/kairo_attack_02_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 554,
    "frameHeight": 435,
    "frameCount": 6,
    "fps": 11,
    "loop": false
  },
  "characters.kairo.hit": {
    "url": "characters/kairo/hit.png",
    "source": "Assets/sprites/kairo/kairo_hit_reaction_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 445,
    "frameHeight": 386,
    "frameCount": 4,
    "fps": 12,
    "loop": false
  },
  "characters.kairo.idle": {
    "url": "characters/kairo/idle.png",
    "source": "Assets/sprites/kairo/01_kairo_idle_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 282,
    "frameHeight": 388,
    "frameCount": 8,
    "fps": 8,
    "loop": true
  },
  "characters.kairo.knockdown": {
    "url": "characters/kairo/knockdown.png",
    "source": "Assets/sprites/kairo/kairo_knockdown_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 475,
    "frameHeight": 371,
    "frameCount": 6,
    "fps": 9,
    "loop": false
  },
  "characters.kairo.run": {
    "url": "characters/kairo/run.png",
    "source": "Assets/sprites/kairo/04_kairo_run_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 483,
    "frameHeight": 374,
    "frameCount": 8,
    "fps": 12,
    "loop": true
  },
  "characters.kairo.walk": {
    "url": "characters/kairo/walk.png",
    "source": "Assets/sprites/kairo/02_kairo_walk_forward_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 315,
    "frameHeight": 389,
    "frameCount": 8,
    "fps": 10,
    "loop": true
  },
  "characters.kairo.walkback": {
    "url": "characters/kairo/walkback.png",
    "source": "Assets/sprites/kairo/03_kairo_walk_backward_hd_sheet.png",
    "bakedStandingPx": 380,
    "frameWidth": 435,
    "frameHeight": 391,
    "frameCount": 8,
    "fps": 10,
    "loop": true
  },
  "characters.raider.attack": {
    "url": "characters/raider/attack.png",
    "source": "Assets/sprites/raider/09_raider_attack_01_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 828,
    "frameHeight": 439,
    "frameCount": 8,
    "fps": 12,
    "loop": false
  },
  "characters.raider.attack2": {
    "url": "characters/raider/attack2.png",
    "source": "Assets/sprites/raider/10_raider_attack_02_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 741,
    "frameHeight": 433,
    "frameCount": 8,
    "fps": 12,
    "loop": false
  },
  "characters.raider.block": {
    "url": "characters/raider/block.png",
    "source": "Assets/sprites/raider/11_raider_block_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 503,
    "frameHeight": 485,
    "frameCount": 4,
    "fps": 10,
    "loop": true
  },
  "characters.raider.defeat": {
    "url": "characters/raider/defeat.png",
    "source": "Assets/sprites/raider/15_raider_defeat_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 650,
    "frameHeight": 403,
    "frameCount": 8,
    "fps": 9,
    "loop": false
  },
  "characters.raider.dodge": {
    "url": "characters/raider/dodge.png",
    "source": "Assets/sprites/raider/12_raider_dodge_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 732,
    "frameHeight": 452,
    "frameCount": 6,
    "fps": 14,
    "loop": false
  },
  "characters.raider.hit": {
    "url": "characters/raider/hit.png",
    "source": "Assets/sprites/raider/13_raider_hit_reaction_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 689,
    "frameHeight": 462,
    "frameCount": 6,
    "fps": 12,
    "loop": false
  },
  "characters.raider.idle": {
    "url": "characters/raider/idle.png",
    "source": "Assets/sprites/raider/06_raider_idle_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 593,
    "frameHeight": 442,
    "frameCount": 8,
    "fps": 8,
    "loop": true
  },
  "characters.raider.knockdown": {
    "url": "characters/raider/knockdown.png",
    "source": "Assets/sprites/raider/14_raider_knockdown_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 561,
    "frameHeight": 406,
    "frameCount": 8,
    "fps": 9,
    "loop": false
  },
  "characters.raider.run": {
    "url": "characters/raider/run.png",
    "source": "Assets/sprites/raider/08_raider_run_chase_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 793,
    "frameHeight": 432,
    "frameCount": 8,
    "fps": 12,
    "loop": true
  },
  "characters.raider.walk": {
    "url": "characters/raider/walk.png",
    "source": "Assets/sprites/raider/07_raider_walk_forward_hd_sheet.png",
    "bakedStandingPx": 430,
    "frameWidth": 696,
    "frameHeight": 433,
    "frameCount": 8,
    "fps": 10,
    "loop": true
  },
  "characters.vael.attack": {
    "url": "characters/vael/attack.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_attack_01_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 842,
    "frameHeight": 490,
    "frameCount": 6,
    "fps": 12,
    "loop": false
  },
  "characters.vael.attack2": {
    "url": "characters/vael/attack2.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_attack_02_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 881,
    "frameHeight": 577,
    "frameCount": 7,
    "fps": 12,
    "loop": false
  },
  "characters.vael.block": {
    "url": "characters/vael/block.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_block_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 496,
    "frameHeight": 482,
    "frameCount": 4,
    "fps": 9,
    "loop": true
  },
  "characters.vael.defeat": {
    "url": "characters/vael/defeat.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_defeat_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 752,
    "frameHeight": 452,
    "frameCount": 6,
    "fps": 9,
    "loop": false
  },
  "characters.vael.dodge": {
    "url": "characters/vael/dodge.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_dodge_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 741,
    "frameHeight": 443,
    "frameCount": 6,
    "fps": 13,
    "loop": false
  },
  "characters.vael.hit": {
    "url": "characters/vael/hit.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_hit_reaction_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 738,
    "frameHeight": 473,
    "frameCount": 4,
    "fps": 12,
    "loop": false
  },
  "characters.vael.idle": {
    "url": "characters/vael/idle.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_idle_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 635,
    "frameHeight": 460,
    "frameCount": 8,
    "fps": 7,
    "loop": true
  },
  "characters.vael.knockdown": {
    "url": "characters/vael/knockdown.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_knockdown_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 847,
    "frameHeight": 434,
    "frameCount": 6,
    "fps": 9,
    "loop": false
  },
  "characters.vael.run": {
    "url": "characters/vael/run.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_run_chase_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 695,
    "frameHeight": 411,
    "frameCount": 8,
    "fps": 12,
    "loop": true
  },
  "characters.vael.walk": {
    "url": "characters/vael/walk.png",
    "source": "Assets/sprites/vael/_vael_hd_new/CHROMA_CLASH_VAEL_GREENSCREEN_HD_10_SEPARATE/vael_walk_forward_hd_sheet.png",
    "bakedStandingPx": 456,
    "frameWidth": 687,
    "frameHeight": 460,
    "frameCount": 8,
    "fps": 10,
    "loop": true
  },
  "vfx.movement.dash_dust": {
    "url": "vfx/movement/dash_dust.png",
    "source": "Assets/vfx/movement/01_dash_dust_sheet.png",
    "frameWidth": 504,
    "frameHeight": 505,
    "frameCount": 6,
    "fps": 18,
    "loop": false
  },
  "vfx.movement.landing_dust": {
    "url": "vfx/movement/landing_dust.png",
    "source": "Assets/vfx/movement/03_landing_dust_sheet.png",
    "frameWidth": 503,
    "frameHeight": 503,
    "frameCount": 6,
    "fps": 18,
    "loop": false
  }
} as const satisfies Record<string, ProcessedAnimation>;

export const PROCESSED_STILLS = {
  "arena.prismfall.arch_broken": {
    "url": "arena/prismfall/arch_broken.png",
    "source": "Assets/arena/prismfall_courtyard/midground/03_arena_midground_architecture_sheet.png",
    "width": 255,
    "height": 165
  },
  "arena.prismfall.arch_full": {
    "url": "arena/prismfall/arch_full.png",
    "source": "Assets/arena/prismfall_courtyard/midground/03_arena_midground_architecture_sheet.png",
    "width": 188,
    "height": 187
  },
  "arena.prismfall.column_a": {
    "url": "arena/prismfall/column_a.png",
    "source": "Assets/arena/prismfall_courtyard/midground/03_arena_midground_architecture_sheet.png",
    "width": 62,
    "height": 203
  },
  "arena.prismfall.column_b": {
    "url": "arena/prismfall/column_b.png",
    "source": "Assets/arena/prismfall_courtyard/midground/03_arena_midground_architecture_sheet.png",
    "width": 81,
    "height": 196
  },
  "arena.prismfall.depth_haze": {
    "url": "arena/prismfall/depth_haze.png",
    "source": "Assets/arena/prismfall_courtyard/far_background/02_arena_far_background_layer_sheet.png",
    "width": 542,
    "height": 148
  },
  "arena.prismfall.distant_mountains": {
    "url": "arena/prismfall/distant_mountains.png",
    "source": "Assets/arena/prismfall_courtyard/far_background/02_arena_far_background_layer_sheet.png",
    "width": 542,
    "height": 147
  },
  "arena.prismfall.far_ruins": {
    "url": "arena/prismfall/far_ruins.png",
    "source": "Assets/arena/prismfall_courtyard/far_background/02_arena_far_background_layer_sheet.png",
    "width": 543,
    "height": 149
  },
  "arena.prismfall.far_sky": {
    "url": "arena/prismfall/far_sky.png",
    "source": "Assets/arena/prismfall_courtyard/far_background/02_arena_far_background_layer_sheet.png",
    "width": 542,
    "height": 144
  },
  "arena.prismfall.floating_islands": {
    "url": "arena/prismfall/floating_islands.png",
    "source": "Assets/arena/prismfall_courtyard/far_background/02_arena_far_background_layer_sheet.png",
    "width": 542,
    "height": 148
  },
  "arena.prismfall.floor_strip": {
    "url": "arena/prismfall/floor_strip.png",
    "source": "Assets/arena/prismfall_courtyard/floor/04_arena_combat_floor_sheet.png",
    "width": 670,
    "height": 131
  },
  "arena.prismfall.floor_tile_a": {
    "url": "arena/prismfall/floor_tile_a.png",
    "source": "Assets/arena/prismfall_courtyard/floor/04_arena_combat_floor_sheet.png",
    "width": 134,
    "height": 131
  },
  "arena.prismfall.floor_tile_b": {
    "url": "arena/prismfall/floor_tile_b.png",
    "source": "Assets/arena/prismfall_courtyard/floor/04_arena_combat_floor_sheet.png",
    "width": 134,
    "height": 130
  },
  "arena.prismfall.ground_mist": {
    "url": "arena/prismfall/ground_mist.png",
    "source": "Assets/arena/prismfall_courtyard/atmosphere/07_arena_atmospheric_overlay_sheet.png",
    "width": 325,
    "height": 84
  },
  "arena.prismfall.wall_section": {
    "url": "arena/prismfall/wall_section.png",
    "source": "Assets/arena/prismfall_courtyard/midground/03_arena_midground_architecture_sheet.png",
    "width": 180,
    "height": 139
  },
  "branding.logo_badge": {
    "url": "branding/logo_badge.png",
    "source": "Assets/branding/logo/01_game_logo_title_lockup_sheet.png",
    "width": 393,
    "height": 332
  },
  "branding.logo_stacked": {
    "url": "branding/logo_stacked.png",
    "source": "Assets/branding/logo/01_game_logo_title_lockup_sheet.png",
    "width": 395,
    "height": 333
  },
  "branding.main_logo": {
    "url": "branding/main_logo.png",
    "source": "Assets/branding/logo/main logo.png",
    "width": 1942,
    "height": 690
  },
  "ui.controls.attack_default": {
    "url": "ui/controls/attack_default.png",
    "source": "Assets/ui/controls/01_attack_button_sheet.png",
    "width": 348,
    "height": 341
  },
  "ui.controls.attack_pressed": {
    "url": "ui/controls/attack_pressed.png",
    "source": "Assets/ui/controls/01_attack_button_sheet.png",
    "width": 340,
    "height": 333
  },
  "ui.controls.block_default": {
    "url": "ui/controls/block_default.png",
    "source": "Assets/ui/controls/04_movement_control_sheet.png",
    "width": 357,
    "height": 350
  },
  "ui.controls.block_pressed": {
    "url": "ui/controls/block_pressed.png",
    "source": "Assets/ui/controls/04_movement_control_sheet.png",
    "width": 352,
    "height": 345
  },
  "ui.controls.heavy_default": {
    "url": "ui/controls/heavy_default.png",
    "source": "Assets/ui/controls/01_attack_button_sheet.png",
    "width": 356,
    "height": 349
  },
  "ui.controls.heavy_pressed": {
    "url": "ui/controls/heavy_pressed.png",
    "source": "Assets/ui/controls/01_attack_button_sheet.png",
    "width": 352,
    "height": 345
  },
  "ui.controls.move_left_default": {
    "url": "ui/controls/move_left_default.png",
    "source": "Assets/ui/hud/06_fight_ready_go_overlay_sheet.png",
    "width": 271,
    "height": 266
  },
  "ui.controls.move_left_pressed": {
    "url": "ui/controls/move_left_pressed.png",
    "source": "Assets/ui/hud/06_fight_ready_go_overlay_sheet.png",
    "width": 275,
    "height": 270
  },
  "ui.controls.move_right_default": {
    "url": "ui/controls/move_right_default.png",
    "source": "Assets/ui/hud/06_fight_ready_go_overlay_sheet.png",
    "width": 285,
    "height": 279
  },
  "ui.controls.move_right_pressed": {
    "url": "ui/controls/move_right_pressed.png",
    "source": "Assets/ui/hud/06_fight_ready_go_overlay_sheet.png",
    "width": 278,
    "height": 272
  },
  "ui.controls.pause_default": {
    "url": "ui/controls/pause_default.png",
    "source": "Assets/ui/controls/03_special_ability_button_sheet.png",
    "width": 309,
    "height": 303
  },
  "ui.controls.pause_pressed": {
    "url": "ui/controls/pause_pressed.png",
    "source": "Assets/ui/controls/03_special_ability_button_sheet.png",
    "width": 308,
    "height": 302
  },
  "ui.controls.special_disabled": {
    "url": "ui/controls/special_disabled.png",
    "source": "Assets/ui/controls/05_pause_settings_control_sheet.png",
    "width": 338,
    "height": 331
  },
  "ui.controls.special_ready": {
    "url": "ui/controls/special_ready.png",
    "source": "Assets/ui/controls/05_pause_settings_control_sheet.png",
    "width": 352,
    "height": 345
  },
  "ui.hud.combo.combo_x10": {
    "url": "ui/hud/combo/combo_x10.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 654,
    "height": 223
  },
  "ui.hud.combo.combo_x15": {
    "url": "ui/hud/combo/combo_x15.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 655,
    "height": 232
  },
  "ui.hud.combo.combo_x2": {
    "url": "ui/hud/combo/combo_x2.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 670,
    "height": 222
  },
  "ui.hud.combo.combo_x3": {
    "url": "ui/hud/combo/combo_x3.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 622,
    "height": 207
  },
  "ui.hud.combo.combo_x30": {
    "url": "ui/hud/combo/combo_x30.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 693,
    "height": 240
  },
  "ui.hud.combo.combo_x5": {
    "url": "ui/hud/combo/combo_x5.png",
    "source": "Assets/ui/hud/combo_badge_design_grid.png",
    "width": 671,
    "height": 212
  },
  "ui.hud.energy_bar.fill_full": {
    "url": "ui/hud/energy_bar/fill_full.png",
    "source": "Assets/ui/hud/neon_sci_fi_energy_bar_reference_sheet.png",
    "width": 676,
    "height": 113
  },
  "ui.hud.energy_bar.frame_empty": {
    "url": "ui/hud/energy_bar/frame_empty.png",
    "source": "Assets/ui/hud/neon_sci_fi_energy_bar_reference_sheet.png",
    "width": 676,
    "height": 113
  },
  "ui.hud.health_bar.fill_full": {
    "url": "ui/hud/health_bar/fill_full.png",
    "source": "Assets/ui/hud/futuristic_health_bar_ui_sheet.png",
    "width": 1140,
    "height": 109
  },
  "ui.hud.health_bar.frame_empty": {
    "url": "ui/hud/health_bar/frame_empty.png",
    "source": "Assets/ui/hud/futuristic_health_bar_ui_sheet.png",
    "width": 1140,
    "height": 109
  },
  "ui.hud.health_bar.frame_warning": {
    "url": "ui/hud/health_bar/frame_warning.png",
    "source": "Assets/ui/hud/futuristic_health_bar_ui_sheet.png",
    "width": 1142,
    "height": 126
  },
  "ui.hud.overlay_fight": {
    "url": "ui/hud/overlay_fight.png",
    "source": "Assets/ui/menus/fight.png",
    "width": 1672,
    "height": 941,
    "passthrough": true,
    "contentRect": {
      "x": 3,
      "y": 179,
      "w": 1668,
      "h": 541
    }
  },
  "ui.hud.overlay_final_fight": {
    "url": "ui/hud/overlay_final_fight.png",
    "source": "Assets/ui/results/08_score_rank_hud_sheet.png",
    "width": 762,
    "height": 248
  },
  "ui.hud.overlay_ko": {
    "url": "ui/hud/overlay_ko.png",
    "source": "Assets/ui/menus/ko.png",
    "width": 1254,
    "height": 1254,
    "passthrough": true,
    "contentRect": {
      "x": 9,
      "y": 283,
      "w": 1235,
      "h": 642
    }
  },
  "ui.hud.overlay_ready": {
    "url": "ui/hud/overlay_ready.png",
    "source": "Assets/ui/menus/ready.png",
    "width": 1672,
    "height": 941,
    "passthrough": true,
    "contentRect": {
      "x": 8,
      "y": 179,
      "w": 1656,
      "h": 539
    }
  },
  "ui.hud.vael_nameplate": {
    "url": "ui/hud/vael_nameplate.png",
    "source": "Assets/ui/hud/07_boss_health_nameplate_sheet.png",
    "width": 708,
    "height": 187
  },
  "ui.tutorial_page": {
    "url": "ui/tutorial_page.png",
    "source": "Assets/ui/tutorial/tutorial.png",
    "width": 1536,
    "height": 1024
  },
  "ui.upgrades.card_default": {
    "url": "ui/upgrades/card_default.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 374,
    "height": 566
  },
  "ui.upgrades.card_locked": {
    "url": "ui/upgrades/card_locked.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 363,
    "height": 560
  },
  "ui.upgrades.card_selected": {
    "url": "ui/upgrades/card_selected.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 421,
    "height": 573
  },
  "ui.upgrades.icon_combo": {
    "url": "ui/upgrades/icon_combo.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 145,
    "height": 162
  },
  "ui.upgrades.icon_damage": {
    "url": "ui/upgrades/icon_damage.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 145,
    "height": 179
  },
  "ui.upgrades.icon_energy": {
    "url": "ui/upgrades/icon_energy.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 145,
    "height": 179
  },
  "ui.upgrades.icon_guard": {
    "url": "ui/upgrades/icon_guard.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 145,
    "height": 179
  },
  "ui.upgrades.icon_health": {
    "url": "ui/upgrades/icon_health.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 145,
    "height": 163
  },
  "ui.upgrades.icon_special": {
    "url": "ui/upgrades/icon_special.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 139,
    "height": 179
  },
  "ui.upgrades.icon_speed": {
    "url": "ui/upgrades/icon_speed.png",
    "source": "Assets/ui/upgrades/08_upgrade_choice_ui_icon_sheet.png",
    "width": 139,
    "height": 162
  },
  "ui.weapons.axe": {
    "url": "ui/weapons/axe.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 355,
    "height": 361
  },
  "ui.weapons.axe_selected": {
    "url": "ui/weapons/axe_selected.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 350,
    "height": 364
  },
  "ui.weapons.blade": {
    "url": "ui/weapons/blade.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 351,
    "height": 384
  },
  "ui.weapons.blade_selected": {
    "url": "ui/weapons/blade_selected.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 346,
    "height": 390
  },
  "ui.weapons.dual": {
    "url": "ui/weapons/dual.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 356,
    "height": 365
  },
  "ui.weapons.dual_selected": {
    "url": "ui/weapons/dual_selected.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 362,
    "height": 380
  },
  "ui.weapons.locked": {
    "url": "ui/weapons/locked.png",
    "source": "Assets/weapons/kairo/icons/05_kairo_weapon_selection_icon_sheet.png",
    "width": 345,
    "height": 365
  },
  "vfx.guardian.hammer_impact": {
    "url": "vfx/guardian/hammer_impact.png",
    "source": "Assets/vfx/guardian/02_guardian_hammer_impact_vfx_sheet.png",
    "width": 188,
    "height": 170
  },
  "vfx.kairo.chroma_burst_main": {
    "url": "vfx/kairo/chroma_burst_main.png",
    "source": "Assets/vfx/kairo/06_kairo_chroma_burst_special_vfx_sheet.png",
    "width": 652,
    "height": 434
  },
  "vfx.kairo.chroma_flash": {
    "url": "vfx/kairo/chroma_flash.png",
    "source": "Assets/vfx/kairo/06_kairo_chroma_burst_special_vfx_sheet.png",
    "width": 322,
    "height": 327
  },
  "vfx.kairo.chroma_ring": {
    "url": "vfx/kairo/chroma_ring.png",
    "source": "Assets/vfx/kairo/06_kairo_chroma_burst_special_vfx_sheet.png",
    "width": 434,
    "height": 369
  },
  "vfx.kairo.heavy_arc": {
    "url": "vfx/kairo/heavy_arc.png",
    "source": "Assets/vfx/kairo/07_kairo_weapon_attack_trail_vfx_sheet.png",
    "width": 667,
    "height": 401
  },
  "vfx.raider.slash_arc": {
    "url": "vfx/raider/slash_arc.png",
    "source": "Assets/vfx/raider/01_raider_slash_vfx_sheet.png",
    "width": 177,
    "height": 128
  },
  "vfx.shared.block_shield": {
    "url": "vfx/shared/block_shield.png",
    "source": "Assets/vfx/shared_combat/06_hit_block_ko_vfx_sheet.png",
    "width": 92,
    "height": 102
  },
  "vfx.shared.boss_defeat_ground": {
    "url": "vfx/shared/boss_defeat_ground.png",
    "source": "Assets/vfx/shared_combat/08_final_victory_boss_defeat_vfx_sheet.png",
    "width": 307,
    "height": 164
  },
  "vfx.shared.boss_defeat_pillar": {
    "url": "vfx/shared/boss_defeat_pillar.png",
    "source": "Assets/vfx/shared_combat/08_final_victory_boss_defeat_vfx_sheet.png",
    "width": 163,
    "height": 336
  },
  "vfx.shared.hit_spark_blue": {
    "url": "vfx/shared/hit_spark_blue.png",
    "source": "Assets/vfx/shared_combat/06_hit_block_ko_vfx_sheet.png",
    "width": 92,
    "height": 100
  },
  "vfx.shared.hit_spark_red": {
    "url": "vfx/shared/hit_spark_red.png",
    "source": "Assets/vfx/shared_combat/06_hit_block_ko_vfx_sheet.png",
    "width": 92,
    "height": 100
  },
  "vfx.shared.ko_burst": {
    "url": "vfx/shared/ko_burst.png",
    "source": "Assets/vfx/shared_combat/06_hit_block_ko_vfx_sheet.png",
    "width": 85,
    "height": 95
  },
  "vfx.vael.aura_crest": {
    "url": "vfx/vael/aura_crest.png",
    "source": "Assets/vfx/vael/05_boss_aura_phase_vfx_sheet.png",
    "width": 165,
    "height": 118
  },
  "vfx.vael.aura_ring": {
    "url": "vfx/vael/aura_ring.png",
    "source": "Assets/vfx/vael/05_boss_aura_phase_vfx_sheet.png",
    "width": 180,
    "height": 77
  },
  "vfx.vael.rift_burst": {
    "url": "vfx/vael/rift_burst.png",
    "source": "Assets/vfx/vael/04_vael_special_attack_vfx_sheet.png",
    "width": 188,
    "height": 170
  },
  "vfx.vael.rift_ring": {
    "url": "vfx/vael/rift_ring.png",
    "source": "Assets/vfx/vael/04_vael_special_attack_vfx_sheet.png",
    "width": 188,
    "height": 170
  },
  "vfx.vael.slash_trail": {
    "url": "vfx/vael/slash_trail.png",
    "source": "Assets/vfx/vael/03_vael_slash_trail_vfx_sheet.png",
    "width": 226,
    "height": 110
  }
} as const satisfies Record<string, ProcessedStill>;

export type AnimationAssetKey = keyof typeof PROCESSED_ANIMATIONS;
export type StillAssetKey = keyof typeof PROCESSED_STILLS;
