/**
 * tools/build-asset-manifest.ts
 *
 * Merges the workspace audit (audit.json), the human-authored classification
 * data (manifest-data.json), the slicing config (assets.config.json) and the
 * processing metadata into:
 *
 *   docs/ASSET_MANIFEST.md            human-readable manifest
 *   src/game/data/assetManifest.ts    typed manifest used at runtime
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');

interface AuditRecord {
  id: string;
  fileName: string;
  extension: string;
  sourcePath: string;
  bytes: number;
  width: number | null;
  height: number | null;
  hasAlpha: boolean | null;
  isChromaGreen: boolean | null;
}

interface ManifestDataEntry {
  category: string;
  system: string;
  classification: string;
  use: string;
  wired: boolean;
  scene: string | null;
  note?: string;
  contentNote?: string;
}

async function main(): Promise<void> {
  const audit = JSON.parse(
    await fs.readFile(path.join(ROOT, 'assets_processed', 'metadata', 'audit.json'), 'utf8'),
  ) as { records: AuditRecord[] };
  const data = JSON.parse(await fs.readFile(path.join(ROOT, 'tools', 'manifest-data.json'), 'utf8')) as {
    assets: Record<string, ManifestDataEntry>;
  };
  const config = JSON.parse(await fs.readFile(path.join(ROOT, 'assets.config.json'), 'utf8')) as {
    entries: Array<{ id: string; source: string }>;
  };

  // processed outputs per source
  const metaDir = path.join(ROOT, 'assets_processed', 'metadata');
  const processedBySource = new Map<string, string[]>();
  for (const f of await fs.readdir(metaDir)) {
    if (!f.endsWith('.json') || f === 'audit.json') continue;
    const meta = JSON.parse(await fs.readFile(path.join(metaDir, f), 'utf8')) as {
      source?: string;
      processedPath?: string;
    };
    if (meta.source && meta.processedPath) {
      const list = processedBySource.get(meta.source) ?? [];
      list.push(meta.processedPath);
      processedBySource.set(meta.source, list);
    }
  }

  const missing: string[] = [];
  const rows = audit.records.map((rec) => {
    const d = data.assets[rec.sourcePath];
    if (!d) missing.push(rec.sourcePath);
    const processed = (processedBySource.get(rec.sourcePath) ?? []).sort();
    return {
      id: rec.id,
      fileName: rec.fileName,
      sourcePath: rec.sourcePath,
      category: d?.category ?? 'UNCLASSIFIED',
      system: d?.system ?? 'UNCLASSIFIED',
      classification: d?.classification ?? 'needs-review',
      expectedUse: d?.use ?? 'UNCLASSIFIED — add to tools/manifest-data.json',
      processingStatus: processed.length > 0 ? 'processed' : d?.classification === 'reference-only' ? 'not-applicable' : 'pending',
      processedPaths: processed,
      runtimeScene: d?.scene ?? null,
      wired: d?.wired ?? false,
      notes: [d?.note, d?.contentNote].filter(Boolean).join(' | ') || '',
      width: rec.width,
      height: rec.height,
      hasAlpha: rec.hasAlpha,
      isChromaGreen: rec.isChromaGreen,
    };
  });

  if (missing.length > 0) {
    console.error(`UNCLASSIFIED assets (add to tools/manifest-data.json):\n  ${missing.join('\n  ')}`);
  }

  // ---- docs/ASSET_MANIFEST.md ----
  const md: string[] = [];
  md.push('# Chroma Clash — Asset Manifest');
  md.push('');
  md.push(`Generated by \`npm run assets:manifest\`. ${rows.length} tracked assets. Raw sources under \`Assets/\` are never modified; all processed output lives in \`assets_processed/\`.`);
  md.push('');
  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.classification, (counts.get(r.classification) ?? 0) + 1);
  md.push('| Classification | Count |');
  md.push('|---|---|');
  for (const [k, v] of [...counts.entries()].sort()) md.push(`| ${k} | ${v} |`);
  md.push('');
  md.push('| ID | Source | Class | Use | Processing | Processed output | Scene | Wired | Notes |');
  md.push('|---|---|---|---|---|---|---|---|---|');
  for (const r of rows) {
    md.push(
      `| \`${r.id}\` | \`${r.sourcePath}\` | ${r.classification} | ${r.expectedUse} | ${r.processingStatus} | ${
        r.processedPaths.map((p) => `\`${p}\``).join('<br>') || '—'
      } | ${r.runtimeScene ?? '—'} | ${r.wired ? 'yes' : 'no'} | ${r.notes} |`,
    );
  }
  md.push('');
  await fs.writeFile(path.join(ROOT, 'docs', 'ASSET_MANIFEST.md'), md.join('\n'));

  // ---- src/game/data/assetManifest.ts ----
  const ts = `/**
 * AUTO-GENERATED by tools/build-asset-manifest.ts — do not edit by hand.
 * Run \`npm run assets:manifest\` to regenerate.
 */

export type AssetClassification =
  | 'runtime'
  | 'reference-only'
  | 'source-sheet'
  | 'needs-review'
  | 'planned-runtime';

export interface AssetManifestRecord {
  id: string;
  fileName: string;
  sourcePath: string;
  category: string;
  system: string;
  classification: AssetClassification;
  expectedUse: string;
  processingStatus: 'processed' | 'pending' | 'not-applicable';
  processedPaths: string[];
  runtimeScene: string | null;
  wired: boolean;
  notes: string;
  width: number | null;
  height: number | null;
}

export const ASSET_MANIFEST: readonly AssetManifestRecord[] = ${JSON.stringify(
    rows.map(({ hasAlpha: _a, isChromaGreen: _g, ...r }) => r),
    null,
    2,
  )} as const;
`;
  await fs.mkdir(path.join(ROOT, 'src', 'game', 'data'), { recursive: true });
  await fs.writeFile(path.join(ROOT, 'src', 'game', 'data', 'assetManifest.ts'), ts);

  // ---- src/game/data/processedAssets.ts (runtime loading data) ----
  const animations: Record<string, unknown> = {};
  const stills: Record<string, unknown> = {};
  for (const f of (await fs.readdir(metaDir)).sort()) {
    if (!f.endsWith('.json') || f === 'audit.json') continue;
    const meta = JSON.parse(await fs.readFile(path.join(metaDir, f), 'utf8')) as Record<string, unknown>;
    if (!meta.processedPath) continue;
    // processedPath is 'assets_processed/x/y.png'; served from publicDir root as 'x/y.png'
    const url = String(meta.processedPath).replace(/^assets_processed\//u, '');
    const key = url.replace(/\.png$/u, '').replace(/\//gu, '.');
    if (meta.kind === 'animation') {
      animations[key] = {
        url,
        source: meta.source,
        ...(meta.bakedStandingPx != null ? { bakedStandingPx: meta.bakedStandingPx } : {}),
        frameWidth: meta.frameWidth,
        frameHeight: meta.frameHeight,
        frameCount: meta.frameCount,
        fps: meta.fps,
        loop: meta.loop,
      };
    } else {
      stills[key] = {
        url,
        source: meta.source,
        width: meta.width,
        height: meta.height,
        ...(meta.passthrough ? { passthrough: true } : {}),
        ...(meta.contentRect ? { contentRect: meta.contentRect } : {}),
      };
    }
  }
  const pa = `/**
 * AUTO-GENERATED by tools/build-asset-manifest.ts — do not edit by hand.
 * Runtime loading data for processed assets (URLs relative to the public root).
 */

export interface ProcessedAnimation {
  url: string;
  source: string;
  /** baked standing height in texture px — runtime scale = worldHeight / this */
  bakedStandingPx?: number;
  frameWidth: number;
  frameHeight: number;
  frameCount: number;
  fps: number;
  loop: boolean;
}

export interface ProcessedStill {
  url: string;
  source: string;
  width: number;
  height: number;
  /** true when the runtime file is a byte-for-byte copy of the source */
  passthrough?: boolean;
  /** visible (non-transparent) bounds inside the image */
  contentRect?: { x: number; y: number; w: number; h: number };
}

export const PROCESSED_ANIMATIONS = ${JSON.stringify(animations, null, 2)} as const satisfies Record<string, ProcessedAnimation>;

export const PROCESSED_STILLS = ${JSON.stringify(stills, null, 2)} as const satisfies Record<string, ProcessedStill>;

export type AnimationAssetKey = keyof typeof PROCESSED_ANIMATIONS;
export type StillAssetKey = keyof typeof PROCESSED_STILLS;
`;
  await fs.writeFile(path.join(ROOT, 'src', 'game', 'data', 'processedAssets.ts'), pa);
  console.log(`manifest: ${rows.length} assets (${missing.length} unclassified), ${config.entries.length} processing entries, ${Object.keys(animations).length} animations, ${Object.keys(stills).length} stills`);
  if (missing.length > 0) process.exitCode = 1;
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
