/**
 * tools/generate-combat-audio.ts
 *
 * Offline combat-audio renderer. Produces ORIGINAL, project-owned sound
 * files with layered DSP synthesis (filtered noise sweeps, inharmonic metal
 * partials, formant-filtered vocal grunts) — the techniques used for real
 * stylized game SFX, not UI beeps. Output: 16-bit mono 44.1 kHz WAV under
 * assets_processed/audio/ (the runtime public dir).
 *
 *   npm run assets:audio
 *
 * Licensing: everything rendered here is generated by this script in-repo,
 * owned by the project (see docs/AUDIO_LICENSES.md).
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'assets_processed', 'audio');
const SR = 44100;

// ------------------------------------------------------------------ utils

type Signal = Float32Array;

function seconds(s: number): number {
  return Math.round(s * SR);
}

function silence(dur: number): Signal {
  return new Float32Array(seconds(dur));
}

/** deterministic per-file RNG so regeneration is reproducible */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 0xffffffff;
  };
}

function whiteNoise(dur: number, seed: number): Signal {
  const r = rng(seed);
  const out = silence(dur);
  for (let i = 0; i < out.length; i++) out[i] = r() * 2 - 1;
  return out;
}

/** oscillator with a per-sample frequency function */
function osc(type: 'sine' | 'saw' | 'square' | 'triangle', dur: number, freqAt: (t: number) => number): Signal {
  const out = silence(dur);
  let phase = 0;
  for (let i = 0; i < out.length; i++) {
    const t = i / SR;
    phase += (freqAt(t) / SR) * 2 * Math.PI;
    const p = phase % (2 * Math.PI);
    if (type === 'sine') out[i] = Math.sin(p);
    else if (type === 'saw') out[i] = (p / Math.PI) - 1;
    else if (type === 'square') out[i] = p < Math.PI ? 1 : -1;
    else out[i] = p < Math.PI ? (p / Math.PI) * 2 - 1 : 3 - (p / Math.PI) * 2;
  }
  return out;
}

/** RBJ biquad with optionally time-varying center frequency */
function biquad(
  input: Signal,
  kind: 'lowpass' | 'highpass' | 'bandpass',
  freqAt: (t: number) => number,
  q = 0.9,
): Signal {
  const out = new Float32Array(input.length);
  let x1 = 0, x2 = 0, y1 = 0, y2 = 0;
  for (let i = 0; i < input.length; i++) {
    const f = Math.min(SR * 0.45, Math.max(30, freqAt(i / SR)));
    const w0 = (2 * Math.PI * f) / SR;
    const alpha = Math.sin(w0) / (2 * q);
    const cosw = Math.cos(w0);
    let b0: number, b1: number, b2: number;
    if (kind === 'lowpass') {
      b0 = (1 - cosw) / 2; b1 = 1 - cosw; b2 = (1 - cosw) / 2;
    } else if (kind === 'highpass') {
      b0 = (1 + cosw) / 2; b1 = -(1 + cosw); b2 = (1 + cosw) / 2;
    } else {
      b0 = alpha; b1 = 0; b2 = -alpha;
    }
    const a0 = 1 + alpha, a1 = -2 * cosw, a2 = 1 - alpha;
    const x0 = input[i]!;
    const y0 = (b0 / a0) * x0 + (b1 / a0) * x1 + (b2 / a0) * x2 - (a1 / a0) * y1 - (a2 / a0) * y2;
    out[i] = y0;
    x2 = x1; x1 = x0; y2 = y1; y1 = y0;
  }
  return out;
}

/** breakpoint envelope: [[time, level], ...] linearly interpolated */
function env(sig: Signal, points: Array<[number, number]>): Signal {
  const out = new Float32Array(sig.length);
  for (let i = 0; i < sig.length; i++) {
    const t = i / SR;
    let level = points[points.length - 1]![1];
    for (let p = 0; p < points.length - 1; p++) {
      const [t0, l0] = points[p]!;
      const [t1, l1] = points[p + 1]!;
      if (t >= t0 && t <= t1) {
        level = l0 + ((t - t0) / Math.max(1e-6, t1 - t0)) * (l1 - l0);
        break;
      }
      if (t < t0) { level = l0; break; }
    }
    out[i] = sig[i]! * level;
  }
  return out;
}

function mix(...layers: Array<{ sig: Signal; gain: number; at?: number }>): Signal {
  const len = Math.max(...layers.map((l) => seconds(l.at ?? 0) + l.sig.length));
  const out = new Float32Array(len);
  for (const l of layers) {
    const off = seconds(l.at ?? 0);
    for (let i = 0; i < l.sig.length; i++) out[off + i]! += l.sig[i]! * l.gain;
  }
  return out;
}

/** normalize to peak then soft-saturate for weight */
function finish(sig: Signal, peak = 0.85, drive = 1.0): Signal {
  let max = 1e-6;
  for (const v of sig) max = Math.max(max, Math.abs(v));
  const out = new Float32Array(sig.length);
  for (let i = 0; i < sig.length; i++) out[i] = Math.tanh((sig[i]! / max) * drive) * peak;
  return out;
}

async function writeWav(rel: string, sig: Signal): Promise<void> {
  const abs = path.join(OUT, rel);
  await fs.mkdir(path.dirname(abs), { recursive: true });
  const data = Buffer.alloc(44 + sig.length * 2);
  data.write('RIFF', 0);
  data.writeUInt32LE(36 + sig.length * 2, 4);
  data.write('WAVE', 8);
  data.write('fmt ', 12);
  data.writeUInt32LE(16, 16);
  data.writeUInt16LE(1, 20); // PCM
  data.writeUInt16LE(1, 22); // mono
  data.writeUInt32LE(SR, 24);
  data.writeUInt32LE(SR * 2, 28);
  data.writeUInt16LE(2, 32);
  data.writeUInt16LE(16, 34);
  data.write('data', 36);
  data.writeUInt32LE(sig.length * 2, 40);
  for (let i = 0; i < sig.length; i++) {
    data.writeInt16LE(Math.max(-32768, Math.min(32767, Math.round(sig[i]! * 32767))), 44 + i * 2);
  }
  await fs.writeFile(abs, data);
  console.log(`  ok audio/${rel} (${(sig.length / SR).toFixed(2)}s)`);
}

// ------------------------------------------------------------------ recipes

/** blade whoosh: band-swept air noise with a fast attack */
function whoosh(dur: number, fFrom: number, fTo: number, seed: number, q = 1.6): Signal {
  const n = biquad(whiteNoise(dur, seed), 'bandpass', (t) => fFrom + (fTo - fFrom) * (t / dur), q);
  return env(n, [[0, 0], [dur * 0.12, 1], [dur * 0.55, 0.7], [dur, 0]]);
}

/** blade "shing": high resonant ring layered over a whoosh */
function shing(dur: number, freq: number, seed: number): Signal {
  const ring = biquad(whiteNoise(dur, seed), 'bandpass', () => freq, 14);
  return env(ring, [[0, 0], [0.012, 1], [dur, 0]]);
}

/** body thump: pitched sine drop with punch */
function thump(dur: number, fFrom: number, fTo: number): Signal {
  const body = osc('sine', dur, (t) => fFrom + (fTo - fFrom) * Math.min(1, t / dur));
  return env(body, [[0, 0], [0.006, 1], [dur, 0]]);
}

/** impact crack: tiny wideband burst */
function crack(seed: number, dur = 0.03, hp = 2600): Signal {
  return env(biquad(whiteNoise(dur, seed), 'highpass', () => hp, 0.8), [[0, 1], [dur, 0]]);
}

/** metallic clang from inharmonic decaying partials */
function metal(dur: number, partials: number[], decay = 8): Signal {
  const layers = partials.map((f, i) => {
    const tone = osc('sine', dur, () => f);
    const d = decay * (1 + i * 0.35);
    const out = new Float32Array(tone.length);
    for (let s = 0; s < tone.length; s++) out[s] = tone[s]! * Math.exp((-s / SR) * d);
    return { sig: out, gain: 1 / (i + 1.2) };
  });
  return mix(...layers);
}

/**
 * Non-verbal vocal grunt: sawtooth glottal source with a pitch contour,
 * shaped by two formant bandpass filters + breath noise. `pitch` sets the
 * character's voice register.
 */
function grunt(
  dur: number,
  pitch: number,
  contour: (t: number) => number,
  seed: number,
  opts: { f1?: number; f2?: number; breath?: number } = {},
): Signal {
  const f1 = opts.f1 ?? 620;
  const f2 = opts.f2 ?? 1150;
  const source = osc('saw', dur, (t) => pitch * contour(t) * (1 + 0.015 * Math.sin(2 * Math.PI * 26 * t)));
  const voiced = mix(
    { sig: biquad(source, 'bandpass', () => f1, 3.5), gain: 1 },
    { sig: biquad(source, 'bandpass', () => f2, 4.5), gain: 0.55 },
    { sig: biquad(whiteNoise(dur, seed), 'bandpass', () => f2 * 1.6, 2), gain: opts.breath ?? 0.14 },
  );
  return env(voiced, [[0, 0], [dur * 0.09, 1], [dur * 0.6, 0.75], [dur, 0]]);
}

// ------------------------------------------------------------------ build

async function main(): Promise<void> {
  console.log('[generate-combat-audio] rendering to assets_processed/audio');

  // ---- sword ----
  await writeWav('weapons/sword/whoosh_light_01.wav', finish(mix(
    { sig: whoosh(0.16, 2400, 700, 11), gain: 1 },
    { sig: shing(0.14, 4200, 12), gain: 0.18 },
  )));
  await writeWav('weapons/sword/whoosh_light_02.wav', finish(mix(
    { sig: whoosh(0.14, 2800, 900, 21), gain: 1 },
    { sig: shing(0.12, 4800, 22), gain: 0.15 },
  )));
  await writeWav('weapons/sword/whoosh_light_03.wav', finish(mix(
    { sig: whoosh(0.18, 2100, 620, 26, 1.5), gain: 1 },
    { sig: shing(0.15, 3800, 27), gain: 0.2 },
  )));
  await writeWav('weapons/sword/whoosh_heavy_01.wav', finish(mix(
    { sig: whoosh(0.26, 1400, 320, 31, 1.2), gain: 1 },
    { sig: whoosh(0.22, 500, 160, 32, 1.0), gain: 0.6 },
    { sig: shing(0.2, 3400, 33), gain: 0.14 },
  ), 0.9));
  await writeWav('weapons/sword/whoosh_heavy_02.wav', finish(mix(
    { sig: whoosh(0.3, 1200, 260, 41, 1.2), gain: 1 },
    { sig: whoosh(0.24, 420, 140, 42, 1.0), gain: 0.65 },
  ), 0.9));
  await writeWav('weapons/sword/dash_01.wav', finish(mix(
    { sig: whoosh(0.22, 600, 2600, 51, 1.3), gain: 1 },
  ), 0.7));

  // ---- hammer ----
  await writeWav('weapons/hammer/swing_heavy_01.wav', finish(mix(
    { sig: whoosh(0.34, 700, 150, 61, 0.9), gain: 1 },
    { sig: whoosh(0.3, 300, 90, 62, 0.8), gain: 0.8 },
  ), 0.95, 1.4));
  await writeWav('weapons/hammer/impact_ground_01.wav', finish(mix(
    { sig: thump(0.35, 150, 34), gain: 1 },
    { sig: crack(63, 0.05, 1400), gain: 0.7 },
    { sig: biquad(whiteNoise(0.3, 64), 'lowpass', (t) => 900 - t * 1800, 0.8), gain: 0.5 },
  ), 0.98, 1.8));

  // ---- impacts ----
  await writeWav('impacts/hit_light_01.wav', finish(mix(
    { sig: thump(0.12, 200, 70), gain: 1 },
    { sig: crack(71), gain: 0.55 },
    { sig: metal(0.09, [1650, 2900], 22), gain: 0.28 }, // blade transient over the body hit
  ), 0.85, 1.4));
  await writeWav('impacts/hit_light_02.wav', finish(mix(
    { sig: thump(0.11, 230, 82), gain: 1 },
    { sig: crack(72, 0.026, 3100), gain: 0.5 },
    { sig: metal(0.08, [1480, 2600], 24), gain: 0.25 },
  ), 0.85, 1.4));
  await writeWav('impacts/hit_heavy_01.wav', finish(mix(
    { sig: thump(0.24, 150, 42), gain: 1 },
    { sig: crack(73, 0.05, 1800), gain: 0.75 },
    { sig: biquad(whiteNoise(0.16, 74), 'lowpass', () => 500, 0.8), gain: 0.45 },
    { sig: metal(0.12, [1180, 2050], 16), gain: 0.3 },
  ), 0.98, 2.0));
  await writeWav('impacts/armor_hit_01.wav', finish(mix(
    { sig: thump(0.14, 170, 60), gain: 0.8 },
    { sig: metal(0.22, [820, 1360, 2210, 3140], 14), gain: 0.7 },
    { sig: crack(75), gain: 0.4 },
  ), 0.9, 1.4));
  await writeWav('impacts/block_metal_01.wav', finish(mix(
    { sig: metal(0.2, [880, 1420, 2600], 16), gain: 1 },
    { sig: crack(81, 0.02, 3600), gain: 0.5 },
  ), 0.8));
  await writeWav('impacts/block_metal_02.wav', finish(mix(
    { sig: metal(0.17, [960, 1620, 2900], 18), gain: 1 },
    { sig: crack(82, 0.02, 4000), gain: 0.45 },
  ), 0.8));
  await writeWav('impacts/parry_01.wav', finish(mix(
    { sig: metal(0.4, [1980, 3420, 5150, 6800], 6), gain: 1 },
    { sig: crack(83, 0.018, 5000), gain: 0.5 },
    { sig: shing(0.3, 6200, 84), gain: 0.3 },
  ), 0.85));
  await writeWav('impacts/guard_break_01.wav', finish(mix(
    { sig: thump(0.34, 190, 36), gain: 1 },
    { sig: metal(0.34, [640, 1080, 1750, 2900], 9), gain: 0.75 },
    { sig: biquad(whiteNoise(0.3, 85), 'lowpass', (t) => 1600 - t * 3600, 0.9), gain: 0.55 },
  ), 0.98, 1.9));

  // ---- movement / misc ----
  await writeWav('misc/jump_01.wav', finish(whoosh(0.16, 500, 1800, 91, 1.4), 0.55));
  await writeWav('misc/land_01.wav', finish(mix(
    { sig: thump(0.12, 130, 62), gain: 1 },
    { sig: crack(92, 0.02, 1200), gain: 0.3 },
  ), 0.6));
  await writeWav('misc/ko_01.wav', finish(mix(
    { sig: thump(0.6, 110, 26), gain: 1 },
    { sig: biquad(whiteNoise(0.5, 93), 'lowpass', (t) => 1200 - t * 1800, 0.8), gain: 0.6 },
    { sig: crack(94, 0.06, 900), gain: 0.6 },
  ), 1.0, 2.2));
  await writeWav('misc/special_01.wav', finish(mix(
    { sig: biquad(whiteNoise(0.55, 95), 'bandpass', (t) => 500 + t * 5200, 2.2), gain: 0.8 },
    { sig: osc('saw', 0.55, (t) => 160 + t * 900), gain: 0.25 },
    { sig: thump(0.4, 120, 40), gain: 0.9, at: 0.32 },
  ), 0.95, 1.4));
  await writeWav('misc/rift_01.wav', finish(mix(
    { sig: biquad(whiteNoise(0.5, 96), 'bandpass', (t) => 3200 - t * 5400, 2.6), gain: 0.9 },
    { sig: osc('saw', 0.5, (t) => 620 - t * 980), gain: 0.3 },
    { sig: metal(0.4, [1120, 1890, 3050], 7), gain: 0.35, at: 0.12 },
  ), 0.9, 1.3));

  // ---- UI (allowed to be synthetic, still musical not raw beeps) ----
  await writeWav('ui/move_01.wav', finish(env(osc('triangle', 0.05, () => 640), [[0, 0], [0.008, 1], [0.05, 0]]), 0.4));
  await writeWav('ui/select_01.wav', finish(env(osc('triangle', 0.1, (t) => 520 + t * 3000), [[0, 0], [0.01, 1], [0.1, 0]]), 0.45));
  await writeWav('ui/denied_01.wav', finish(env(osc('square', 0.13, (t) => 220 - t * 460), [[0, 0], [0.01, 0.8], [0.13, 0]]), 0.4));
  await writeWav('ui/victory_01.wav', finish(mix(
    ...[523.25, 659.26, 783.99, 1046.5].map((f, i) => ({
      sig: env(osc('triangle', 0.34, () => f), [[0, 0], [0.02, 1], [0.34, 0]]),
      gain: 0.55,
      at: i * 0.13,
    })),
  ), 0.7));
  await writeWav('ui/defeat_01.wav', finish(mix(
    ...[392.0, 311.13, 261.63, 196.0].map((f, i) => ({
      sig: env(osc('triangle', 0.4, () => f), [[0, 0], [0.02, 1], [0.4, 0]]),
      gain: 0.55,
      at: i * 0.16,
    })),
  ), 0.7));

  // ---- voices (non-verbal grunts; recorded lines remain future work) ----
  const voices: Array<[string, number, { f1?: number; f2?: number }]> = [
    ['kairo', 150, { f1: 640, f2: 1250 }],
    ['raider', 132, { f1: 600, f2: 1150 }],
    ['guardian', 82, { f1: 470, f2: 900 }],
    ['vael', 104, { f1: 520, f2: 1020 }],
  ];
  let seed = 200;
  for (const [name, pitch, formants] of voices) {
    // attack efforts: short rising "hah"
    await writeWav(`voices/${name}/attack_01.wav`, finish(grunt(0.2, pitch, (t) => 1.05 + t * 0.9, seed++, formants), 0.7));
    await writeWav(`voices/${name}/attack_02.wav`, finish(grunt(0.17, pitch * 1.06, (t) => 1.0 + t * 1.1, seed++, formants), 0.7));
    // hurt: falling "ugh"
    await writeWav(`voices/${name}/hurt_light_01.wav`, finish(grunt(0.22, pitch * 1.16, (t) => 1.25 - t * 1.1, seed++, { ...formants, breath: 0.22 }), 0.7));
    await writeWav(`voices/${name}/hurt_light_02.wav`, finish(grunt(0.2, pitch * 1.1, (t) => 1.2 - t * 0.9, seed++, { ...formants, breath: 0.2 }), 0.7));
    await writeWav(`voices/${name}/hurt_heavy_01.wav`, finish(grunt(0.42, pitch * 1.22, (t) => 1.35 - t * 1.4, seed++, { ...formants, breath: 0.26 }), 0.8));
    // defeat: long falling cry
    await writeWav(`voices/${name}/defeat_01.wav`, finish(grunt(0.75, pitch * 1.1, (t) => 1.3 - t * 1.15, seed++, { ...formants, breath: 0.3 }), 0.8));
  }
  // kairo special shout + vael taunt (two-beat)
  await writeWav('voices/kairo/special_01.wav', finish(grunt(0.5, 155, (t) => 1.0 + Math.min(1, t * 3) * 0.7, 300, { f1: 660, f2: 1300, breath: 0.18 }), 0.85));
  await writeWav('voices/vael/taunt_01.wav', finish(mix(
    { sig: grunt(0.26, 102, (t) => 1.15 - t * 0.5, 301, { f1: 520, f2: 1000 }), gain: 1 },
    { sig: grunt(0.34, 96, (t) => 1.05 - t * 0.6, 302, { f1: 500, f2: 960, breath: 0.2 }), gain: 0.95, at: 0.34 },
  ), 0.8));

  console.log('[generate-combat-audio] done');
}

void main();
