/**
 * tools/validate-asset-usage.ts
 *
 * Enforces the "no asset silently ignored" rule and generates
 * docs/ASSET_USAGE_MATRIX.md.
 *
 * Checks:
 *  1. Every file under Assets/ appears in the audit.
 *  2. Every audited asset has an explicit classification.
 *  3. Every `source-sheet`/`runtime` asset has processed output on disk.
 *  4. Every wired asset names a runtime scene.
 *  5. Raw sources have not been modified (byte size sanity vs audit).
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

async function main(): Promise<void> {
  const problems: string[] = [];
  const audit = JSON.parse(
    await fs.readFile(path.join(ROOT, 'assets_processed', 'metadata', 'audit.json'), 'utf8'),
  ) as { records: Array<{ sourcePath: string; bytes: number }> };
  const data = JSON.parse(await fs.readFile(path.join(ROOT, 'tools', 'manifest-data.json'), 'utf8')) as {
    assets: Record<string, { classification: string; wired: boolean; scene: string | null; use: string; category: string }>;
  };

  const auditPaths = new Set(audit.records.map((r) => r.sourcePath));
  const diskFiles = (await walk(path.join(ROOT, 'Assets'))).map((f) =>
    path.relative(ROOT, f).split(path.sep).join('/'),
  );

  for (const f of diskFiles) {
    if (!auditPaths.has(f)) problems.push(`on disk but not audited: ${f} — re-run npm run assets:audit`);
  }
  for (const r of audit.records) {
    if (!diskFiles.includes(r.sourcePath)) problems.push(`audited but missing on disk: ${r.sourcePath}`);
  }

  // classification coverage
  for (const r of audit.records) {
    if (!data.assets[r.sourcePath]) problems.push(`no classification: ${r.sourcePath}`);
  }
  for (const key of Object.keys(data.assets)) {
    if (!auditPaths.has(key)) problems.push(`classified but not on disk (stale manifest-data): ${key}`);
  }

  // raw sources unmodified (byte-size check vs audit)
  for (const r of audit.records) {
    const stat = await fs.stat(path.join(ROOT, r.sourcePath)).catch(() => null);
    if (stat && stat.size !== r.bytes) {
      problems.push(`RAW SOURCE MODIFIED: ${r.sourcePath} (${r.bytes} -> ${stat.size} bytes)`);
    }
  }

  // processed output exists for source-sheets; wired implies scene
  const metaDir = path.join(ROOT, 'assets_processed', 'metadata');
  const processedBySource = new Map<string, string[]>();
  for (const f of await fs.readdir(metaDir)) {
    if (!f.endsWith('.json') || f === 'audit.json') continue;
    const meta = JSON.parse(await fs.readFile(path.join(metaDir, f), 'utf8')) as {
      source?: string;
      processedPath?: string;
    };
    if (meta.source && meta.processedPath) {
      const list = processedBySource.get(meta.source) ?? [];
      list.push(meta.processedPath);
      processedBySource.set(meta.source, list);
      const abs = path.join(ROOT, meta.processedPath);
      if (!(await fs.stat(abs).catch(() => null))) {
        problems.push(`metadata points at missing processed file: ${meta.processedPath}`);
      }
    }
  }
  for (const [src, d] of Object.entries(data.assets)) {
    if ((d.classification === 'source-sheet' || d.classification === 'runtime') && !processedBySource.has(src)) {
      problems.push(`classified ${d.classification} but no processed output: ${src}`);
    }
    if (d.wired && !d.scene) problems.push(`wired but no runtime scene recorded: ${src}`);
  }

  // ---- usage matrix ----
  const md: string[] = [];
  md.push('# Chroma Clash — Asset Usage Matrix');
  md.push('');
  md.push('Generated by `npm run assets:validate`. Answers: where does every asset end up?');
  md.push('');
  md.push('| Source asset | Classification | Runtime destination | Scene / state | Status |');
  md.push('|---|---|---|---|---|');
  for (const r of audit.records) {
    const d = data.assets[r.sourcePath];
    const outs = processedBySource.get(r.sourcePath) ?? [];
    const dest =
      outs.length > 0
        ? outs.sort().map((o) => `\`${o}\``).join('<br>')
        : d?.classification === 'reference-only'
          ? '_(reference — viewable in Asset Gallery)_'
          : '_(not processed yet)_';
    const status = d?.wired ? 'WIRED' : d?.classification === 'planned-runtime' ? 'PLANNED' : d?.classification === 'needs-review' ? 'NEEDS-REVIEW' : d?.classification === 'reference-only' ? 'PRESERVED' : 'UNKNOWN';
    md.push(`| \`${r.sourcePath}\` | ${d?.classification ?? '??'} | ${dest} | ${d?.scene ?? '—'} | ${status} |`);
  }
  md.push('');
  md.push(`## Validation ${problems.length === 0 ? '— PASS' : `— ${problems.length} problem(s)`}`);
  md.push('');
  for (const p of problems) md.push(`- ${p}`);
  if (problems.length === 0) md.push('No problems found.');
  md.push('');
  await fs.writeFile(path.join(ROOT, 'docs', 'ASSET_USAGE_MATRIX.md'), md.join('\n'));

  // HD integrity: no active Guardian/Vael/Raider animation may resolve to a
  // legacy low-res sheet when an HD replacement exists. The old Vael sheet is
  // allowlisted ONLY for heavy + special (no HD counterparts produced yet).
  const HD_ALLOWLIST = new Set<string>(); // every active fighter strip is HD-sourced now
  for (const f of await fs.readdir(path.join(ROOT, 'assets_processed', 'metadata'))) {
    const m = /^characters__(guardian|vael|raider)__(.+).json$/.exec(f);
    if (!m) continue;
    const meta = JSON.parse(await fs.readFile(path.join(ROOT, 'assets_processed', 'metadata', f), 'utf8')) as { source?: string };
    const stem = f.replace(/.json$/, '');
    if (HD_ALLOWLIST.has(stem)) continue;
    if (meta.source && !meta.source.startsWith('Assets/sprites/')) {
      problems.push(stem + ' resolves to legacy low-res source ' + meta.source + ' — an HD replacement exists');
    }
  }

  console.log(problems.length === 0 ? 'asset usage validation: PASS' : `asset usage validation: ${problems.length} problem(s)`);
  for (const p of problems) console.error(`  - ${p}`);
  if (problems.length > 0) process.exitCode = 1;
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
